import type { Collector, Signal, SourceKind } from "./types";

/**
 * Spinneret scores *changes*, not entries.
 *
 * A company in a directory is not a lead. A company that just opened three
 * revenue roles is — because the budget decision already happened and the need
 * is current. Every rule below is a heuristic about timing, and each one carries
 * its own justification string so the score is never a black box to the operator
 * who has to act on it.
 */

interface ScoringRule {
  id: string;
  pattern: RegExp;
  points: number;
  reason: string;
}

/** Role-function rules: what the hire implies the company is about to buy. */
const FUNCTION_RULES: ScoringRule[] = [
  {
    id: "revenue-role",
    pattern: /\b(account executive|ae|sales engineer|sdr|bdr|revenue|quota)\b/i,
    points: 30,
    reason: "Revenue-carrying role — GTM motion is being scaled, tooling budget follows",
  },
  {
    id: "gtm-leadership",
    pattern: /\b(head of sales|vp sales|cro|vp marketing|cmo|head of growth)\b/i,
    points: 34,
    reason: "GTM leadership hire — new leaders re-tool their stack within one quarter",
  },
  {
    id: "demand-gen",
    pattern: /\b(demand gen|growth marketing|lifecycle|performance marketing)\b/i,
    points: 26,
    reason: "Demand-generation hire — pipeline targets are rising",
  },
  {
    id: "revops",
    pattern: /\b(revops|revenue operations|sales ops|gtm ops)\b/i,
    points: 32,
    reason: "RevOps hire — an explicit mandate to buy and integrate GTM tooling",
  },
  {
    id: "partnerships",
    pattern: /\b(partnerships|alliances|channel)\b/i,
    points: 20,
    reason: "Partnerships hire — expanding distribution surface",
  },
  {
    id: "customer-success",
    pattern: /\b(customer success|account manager|onboarding specialist)\b/i,
    points: 18,
    reason: "Post-sale hire — existing customer base is growing enough to need coverage",
  },
];

/** Seniority rules: how much authority the hire carries. */
const SENIORITY_RULES: ScoringRule[] = [
  {
    id: "exec",
    pattern: /\b(chief|vp|vice president|head of|director)\b/i,
    points: 18,
    reason: "Executive-level opening — budget authority attached",
  },
  {
    id: "lead",
    pattern: /\b(lead|principal|staff|senior manager)\b/i,
    points: 10,
    reason: "Senior opening — team build-out in progress",
  },
];

/** Signals that a company is expanding its footprint. */
const EXPANSION_RULES: ScoringRule[] = [
  {
    id: "remote-global",
    pattern: /\b(worldwide|global|anywhere|emea|apac)\b/i,
    points: 8,
    reason: "Geographically open hire — expanding into new markets",
  },
];

const ALL_RULES = [...FUNCTION_RULES, ...SENIORITY_RULES, ...EXPANSION_RULES];

/** Score bump applied when a company was absent from the previous run. */
const NEW_ENTRANT_POINTS = 22;
/** Score bump per additional concurrent opening at the same company. */
const VOLUME_POINTS_PER_EXTRA_ROLE = 9;
const VOLUME_POINTS_CAP = 27;

const clampScore = (n: number): number => Math.min(100, Math.max(0, Math.round(n)));

/**
 * Collector output field names are generated by an AI and vary per target, so
 * nothing downstream may assume a fixed key. Resolving by candidate list keeps
 * the signal layer working across schema changes — including the ones a heal
 * introduces.
 */
export function resolveField(
  row: Record<string, unknown>,
  candidates: string[],
): string | undefined {
  const keys = Object.keys(row);
  for (const candidate of candidates) {
    const match = keys.find((key) => key.toLowerCase() === candidate.toLowerCase());
    if (match && typeof row[match] === "string" && (row[match] as string).trim()) {
      return (row[match] as string).trim();
    }
  }
  // Fall back to fuzzy containment, e.g. "job_title" matching candidate "title".
  for (const candidate of candidates) {
    const match = keys.find((key) => key.toLowerCase().includes(candidate.toLowerCase()));
    if (match && typeof row[match] === "string" && (row[match] as string).trim()) {
      return (row[match] as string).trim();
    }
  }
  return undefined;
}

const COMPANY_KEYS = ["company", "company_name", "employer", "organization", "name"];
const TITLE_KEYS = ["title", "job_title", "position", "role", "one_liner", "tagline", "description"];
const URL_KEYS = ["company_url", "job_url", "product_page_url", "url", "link", "href"];
const LOCATION_KEYS = ["location", "region", "city", "country"];

/** Apply a rule table to text, accumulating points and their justifications. */
function applyRules(
  text: string,
  rules: ScoringRule[],
  takeHighestOnly: boolean,
): { points: number; rationale: string[] } {
  const hits = rules.filter((rule) => rule.pattern.test(text));
  if (hits.length === 0) return { points: 0, rationale: [] };

  if (takeHighestOnly) {
    const best = hits.reduce((a, b) => (b.points > a.points ? b : a));
    return { points: best.points, rationale: [best.reason] };
  }
  return {
    points: hits.reduce((sum, rule) => sum + rule.points, 0),
    rationale: hits.map((rule) => rule.reason),
  };
}

/**
 * Derive scored signals from one run's rows.
 *
 * `previouslySeen` carries the company set from the prior run; membership is what
 * separates "this company exists" from "this company just appeared", which is the
 * distinction the entire product rests on.
 */
export function deriveSignals(
  collector: Collector,
  rows: Record<string, unknown>[],
  previouslySeen: ReadonlySet<string>,
  detectedAt: string,
): Omit<Signal, "id">[] {
  // Group rows by company so concurrent-opening volume can be scored.
  const byCompany = new Map<string, Record<string, unknown>[]>();
  for (const row of rows) {
    const company = resolveField(row, COMPANY_KEYS);
    if (!company) continue;
    const bucket = byCompany.get(company) ?? [];
    bucket.push(row);
    byCompany.set(company, bucket);
  }

  const signals: Omit<Signal, "id">[] = [];

  for (const [company, companyRows] of byCompany) {
    const rationale: string[] = [];
    let intent = 0;

    const titles = companyRows
      .map((row) => resolveField(row, TITLE_KEYS))
      .filter((title): title is string => Boolean(title));
    const haystack = titles.join(" | ");

    // Function: only the strongest applies, so a single job cannot double-count.
    const fn = applyRules(haystack, FUNCTION_RULES, true);
    intent += fn.points;
    rationale.push(...fn.rationale);

    const seniority = applyRules(haystack, SENIORITY_RULES, true);
    intent += seniority.points;
    rationale.push(...seniority.rationale);

    const locations = companyRows
      .map((row) => resolveField(row, LOCATION_KEYS))
      .filter((loc): loc is string => Boolean(loc))
      .join(" | ");
    const expansion = applyRules(locations || haystack, EXPANSION_RULES, true);
    intent += expansion.points;
    rationale.push(...expansion.rationale);

    if (!previouslySeen.has(company)) {
      intent += NEW_ENTRANT_POINTS;
      rationale.push(
        previouslySeen.size === 0
          ? "First observation — establishing baseline for future change detection"
          : "Newly appeared since the previous run — the change is fresh",
      );
    }

    if (companyRows.length > 1) {
      const bonus = Math.min(
        VOLUME_POINTS_CAP,
        (companyRows.length - 1) * VOLUME_POINTS_PER_EXTRA_ROLE,
      );
      intent += bonus;
      rationale.push(
        `${companyRows.length} concurrent openings — coordinated team build-out, not backfill`,
      );
    }

    if (rationale.length === 0) continue;

    signals.push({
      collectorSlug: collector.slug,
      detectedAt,
      company,
      kind: collector.kind,
      headline: buildHeadline(collector.kind, companyRows.length, titles),
      intent: clampScore(intent),
      rationale,
      sourceUrl: resolveField(companyRows[0], URL_KEYS),
    });
  }

  return signals.sort((a, b) => b.intent - a.intent);
}

function buildHeadline(kind: SourceKind, count: number, titles: string[]): string {
  const sample = titles[0] ?? "role";
  switch (kind) {
    case "hiring":
      return count > 1
        ? `Opened ${count} roles including ${sample}`
        : `Opened a role: ${sample}`;
    case "directory":
      return `Listed in directory: ${sample}`;
    case "changelog":
      return `Shipped: ${sample}`;
    case "pricing":
      return `Pricing page changed: ${sample}`;
  }
}
