import type { Collector, Signal, SourceKind } from "./types";

/**
 * Spinneret scores *changes*, not entries.
 *
 * A company in a directory is not a lead. A company that just opened three
 * revenue roles is — because the budget decision already happened and the need
 * is current. Every rule below is a heuristic about timing, and each one carries
 * its own justification string so the score is never a black box to the operator
 * who has to act on it.
 */

interface ScoringRule {
  id: string;
  pattern: RegExp;
  points: number;
  reason: string;
}

/** Role-function rules: what the hire implies the company is about to buy. */
const FUNCTION_RULES: ScoringRule[] = [
  {
    id: "revenue-role",
    pattern: /\b(account executive|ae|sales engineer|sdr|bdr|revenue|quota)\b/i,
    points: 30,
    reason: "Revenue-carrying role, so the GTM motion is scaling and tooling budget follows",
  },
  {
    id: "gtm-leadership",
    pattern: /\b(head of sales|vp sales|cro|vp marketing|cmo|head of growth)\b/i,
    points: 34,
    reason: "GTM leadership hire, and new leaders re-tool their stack within a quarter",
  },
  {
    id: "demand-gen",
    pattern: /\b(demand gen|growth marketing|lifecycle|performance marketing)\b/i,
    points: 26,
    reason: "Demand-generation hire, which means pipeline targets are rising",
  },
  {
    id: "revops",
    pattern: /\b(revops|revenue operations|sales ops|gtm ops)\b/i,
    points: 32,
    reason: "RevOps hire, an explicit mandate to buy and integrate GTM tooling",
  },
  {
    id: "partnerships",
    pattern: /\b(partnerships|alliances|channel)\b/i,
    points: 20,
    reason: "Partnerships hire, so the company is expanding its distribution surface",
  },
  {
    id: "customer-success",
    pattern: /\b(customer success|account manager|onboarding specialist)\b/i,
    points: 18,
    reason: "Post-sale hire, so the customer base is growing enough to need coverage",
  },
];

/** Seniority rules: how much authority the hire carries. */
const SENIORITY_RULES: ScoringRule[] = [
  {
    id: "exec",
    pattern: /\b(chief|vp|vice president|head of|director)\b/i,
    points: 18,
    reason: "Executive-level opening, which carries budget authority",
  },
  {
    id: "lead",
    pattern: /\b(lead|principal|staff|senior manager)\b/i,
    points: 10,
    reason: "Senior opening, so a team build-out is in progress",
  },
];

/** Signals that a company is expanding its footprint. */
const EXPANSION_RULES: ScoringRule[] = [
  {
    id: "remote-global",
    pattern: /\b(worldwide|global|anywhere|emea|apac)\b/i,
    points: 8,
    reason: "Geographically open hire, so the company is expanding into new markets",
  },
];

/** Changelog rules: what shipping this implies about where the company is going. */
const CHANGELOG_RULES: ScoringRule[] = [
  {
    id: "enterprise-readiness",
    pattern: /\b(sso|saml|scim|audit log|rbac|compliance|soc ?2|enterprise)\b/i,
    points: 34,
    reason: "Shipped enterprise-readiness features, so it is moving upmarket toward larger deals",
  },
  {
    id: "integration-surface",
    pattern: /\b(integration|connector|webhook|api|sdk|import|sync)\b/i,
    points: 26,
    reason: "Expanded integration surface, which points to an ecosystem play",
  },
  {
    id: "ai-investment",
    pattern: /\b(ai|agent|llm|copilot|model|intelligence)\b/i,
    points: 22,
    reason: "Investing in AI capability, which means active budget and roadmap pressure",
  },
  {
    id: "scale-work",
    pattern: /\b(performance|scale|latency|throughput|bulk)\b/i,
    points: 16,
    reason: "Scaling work shipped, so usage is growing faster than the current system",
  },
];

/** Directory rules: how well a listed company fits a B2B software ICP. */
const SECTOR_RULES: ScoringRule[] = [
  {
    id: "b2b-saas",
    pattern: /\b(b2b|saas|platform|infrastructure|developer|api)\b/i,
    points: 24,
    reason: "B2B software company, which buys tooling as a matter of course",
  },
  {
    id: "ai-native",
    pattern: /\b(ai|agent|llm|machine learning|automation)\b/i,
    points: 20,
    reason: "AI-native company, typically well funded and quick to adopt new tooling",
  },
  {
    id: "gtm-adjacent",
    pattern: /\b(sales|marketing|crm|revenue|customer|support)\b/i,
    points: 18,
    reason: "Operates in the GTM space, so it understands and buys this category",
  },
  {
    id: "fintech-health",
    pattern: /\b(fintech|health|insurance|legal|compliance)\b/i,
    points: 14,
    reason: "Regulated vertical, with a higher willingness to pay for reliability",
  },
];

/** Score bump applied when a company was absent from the previous run. */
const NEW_ENTRANT_POINTS = 22;
/** Score bump per additional concurrent opening at the same company. */
const VOLUME_POINTS_PER_EXTRA_ROLE = 9;
const VOLUME_POINTS_CAP = 27;

const clampScore = (n: number): number => Math.min(100, Math.max(0, Math.round(n)));

/**
 * Collector output field names are generated by an AI and vary per target, so
 * nothing downstream may assume a fixed key. Resolving by candidate list keeps
 * the signal layer working across schema changes — including the ones a heal
 * introduces.
 */
export function resolveField(
  row: Record<string, unknown>,
  candidates: string[],
): string | undefined {
  const keys = Object.keys(row);
  for (const candidate of candidates) {
    const match = keys.find((key) => key.toLowerCase() === candidate.toLowerCase());
    if (match && typeof row[match] === "string" && (row[match] as string).trim()) {
      return (row[match] as string).trim();
    }
  }
  // Fall back to fuzzy containment, e.g. "job_title" matching candidate "title".
  for (const candidate of candidates) {
    const match = keys.find((key) => key.toLowerCase().includes(candidate.toLowerCase()));
    if (match && typeof row[match] === "string" && (row[match] as string).trim()) {
      return (row[match] as string).trim();
    }
  }
  return undefined;
}

const COMPANY_KEYS = ["company", "company_name", "employer", "organization", "name"];
const TITLE_KEYS = ["title", "job_title", "position", "role", "one_liner", "tagline", "description"];
const URL_KEYS = ["company_url", "job_url", "product_page_url", "url", "link", "href"];
const LOCATION_KEYS = ["location", "region", "city", "country"];

/** Apply a rule table to text, accumulating points and their justifications. */
function applyRules(
  text: string,
  rules: ScoringRule[],
  takeHighestOnly: boolean,
): { points: number; rationale: string[] } {
  const hits = rules.filter((rule) => rule.pattern.test(text));
  if (hits.length === 0) return { points: 0, rationale: [] };

  if (takeHighestOnly) {
    const best = hits.reduce((a, b) => (b.points > a.points ? b : a));
    return { points: best.points, rationale: [best.reason] };
  }
  return {
    points: hits.reduce((sum, rule) => sum + rule.points, 0),
    rationale: hits.map((rule) => rule.reason),
  };
}

/** Flatten every value in a row to searchable text, arrays included. */
function rowText(row: Record<string, unknown>): string {
  return Object.entries(row)
    .filter(([key]) => key !== "input")
    .map(([, value]) => (Array.isArray(value) ? value.join(" ") : String(value ?? "")))
    .join(" | ");
}

/**
 * Apply the rule set appropriate to the source.
 *
 * A job title, a changelog entry and a directory listing say different things
 * about intent, so each gets its own table rather than one table stretched to
 * cover all three. Only the strongest rule in a table applies, which stops a
 * company with many similar rows from compounding the same evidence.
 */
function scoreByKind(
  kind: SourceKind,
  haystack: string,
  locations: string,
): { points: number; rationale: string[] } {
  const collected: { points: number; rationale: string[] }[] = [];

  if (kind === "hiring") {
    collected.push(applyRules(haystack, FUNCTION_RULES, true));
    collected.push(applyRules(haystack, SENIORITY_RULES, true));
    collected.push(applyRules(locations || haystack, EXPANSION_RULES, true));
  } else if (kind === "changelog" || kind === "pricing") {
    collected.push(applyRules(haystack, CHANGELOG_RULES, true));
  } else {
    collected.push(applyRules(haystack, SECTOR_RULES, true));
  }

  return {
    points: collected.reduce((sum, entry) => sum + entry.points, 0),
    rationale: collected.flatMap((entry) => entry.rationale),
  };
}

/**
 * Derive scored signals from one run's rows.
 *
 * `previouslySeen` carries the company set from prior runs; membership is what
 * separates "this company exists" from "this company just appeared", which is the
 * distinction the entire product rests on.
 */
export function deriveSignals(
  collector: Collector,
  rows: Record<string, unknown>[],
  previouslySeen: ReadonlySet<string>,
  detectedAt: string,
): Omit<Signal, "id">[] {
  // Group rows by company so concurrent activity can be scored together. A
  // single-subject source (a competitor changelog) names its company up front.
  const byCompany = new Map<string, Record<string, unknown>[]>();
  for (const row of rows) {
    const company = collector.subjectCompany ?? resolveField(row, COMPANY_KEYS);
    if (!company) continue;
    const bucket = byCompany.get(company) ?? [];
    bucket.push(row);
    byCompany.set(company, bucket);
  }

  const signals: Omit<Signal, "id">[] = [];

  for (const [company, companyRows] of byCompany) {
    const rationale: string[] = [];
    let intent = 0;

    const titles = companyRows
      .map((row) => resolveField(row, TITLE_KEYS))
      .filter((title): title is string => Boolean(title));

    // Directory and changelog rules match on sector and feature language, which
    // lives across several fields rather than in the title alone.
    const haystack =
      collector.kind === "hiring"
        ? titles.join(" | ")
        : companyRows.map(rowText).join(" | ");

    const locations = companyRows
      .map((row) => resolveField(row, LOCATION_KEYS))
      .filter((loc): loc is string => Boolean(loc))
      .join(" | ");

    const scored = scoreByKind(collector.kind, haystack, locations);
    intent += scored.points;
    rationale.push(...scored.rationale);

    if (!previouslySeen.has(company)) {
      intent += NEW_ENTRANT_POINTS;
      rationale.push(
        previouslySeen.size === 0
          ? "First observation, establishing a baseline for future change detection"
          : "Newly appeared since the previous run, so the change is fresh",
      );
    }

    if (companyRows.length > 1) {
      const bonus = Math.min(
        VOLUME_POINTS_CAP,
        (companyRows.length - 1) * VOLUME_POINTS_PER_EXTRA_ROLE,
      );
      intent += bonus;
      rationale.push(
        collector.kind === "hiring"
          ? `${companyRows.length} concurrent openings, a coordinated build-out rather than backfill`
          : `${companyRows.length} recent entries, which shows sustained shipping velocity`,
      );
    }

    if (rationale.length === 0) continue;

    signals.push({
      collectorSlug: collector.slug,
      detectedAt,
      company,
      kind: collector.kind,
      headline: buildHeadline(collector.kind, companyRows.length, titles),
      intent: clampScore(intent),
      rationale,
      sourceUrl: resolveField(companyRows[0], URL_KEYS),
    });
  }

  return signals.sort((a, b) => b.intent - a.intent);
}

/** Longest headline that stays readable in a table row. */
const HEADLINE_MAX_CHARS = 72;

/**
 * Shorten a title at a word boundary.
 *
 * Scraped titles can run long — a changelog entry often concatenates several
 * release headings into one string — and an unclipped one wraps to three lines
 * and breaks the scan pattern of the board.
 */
export function truncateTitle(title: string, maxChars = HEADLINE_MAX_CHARS): string {
  const collapsed = title.replace(/\s+/g, " ").trim();
  if (collapsed.length <= maxChars) return collapsed;

  const clipped = collapsed.slice(0, maxChars);
  const lastSpace = clipped.lastIndexOf(" ");
  return `${(lastSpace > maxChars * 0.6 ? clipped.slice(0, lastSpace) : clipped).trimEnd()}…`;
}

function buildHeadline(kind: SourceKind, count: number, titles: string[]): string {
  const sample = truncateTitle(titles[0] ?? "role");
  switch (kind) {
    case "hiring":
      return count > 1
        ? `Opened ${count} roles including ${sample}`
        : `Opened a role: ${sample}`;
    case "directory":
      return `Listed in directory: ${sample}`;
    case "changelog":
      return `Shipped: ${sample}`;
    case "pricing":
      return `Pricing page changed: ${sample}`;
  }
}
